### PR TITLE
Typo fix on README

### PR DESCRIPTION
**Pull request by luca-martial**

### CODE REVIEW

**Comment by talgalili** [comment]
Hey @luca-martial - thanks for the quick typo fix!

If you want this diff to be approved, we'll need you to sign off on the contributor license agreement (see here: https://github.com/facebookresearch/balance/pull/15/checks?check_run_id=10603303837 )
If you decide you won't get to it, it's fine, I'll make this change manually later.

**Comment by luca-martial** [comment]
Cheers @talgalili! I signed off on the license agreement, should take a bit of time before the PR gets tagged with `CLA signed`

**Comment by talgalili** [comment]
Hey @luca-martial 
Sorry - but it seems that you need to rebase your PR on top of the latest commit (I don't see how I can do it on your PR).
Is it something you can easily do?
(if yes - great. If not - I can just create another PR for your fix)

Sorry for the extra effort here :)

**Comment by talgalili** [comment]
Update - I've fixed it in another diff, so closing this patch.

Thanks for the report @luca-martial (no fix is too small :) )

**Pull request closed without merging**
