### PR TITLE
Address deprecated pandas syntax

### PR DESCRIPTION
**Pull request by ahakso**
This PR changes a couple minor deprecated pandas syntax choices.

Passing a set is deprecated. This PR converts the set to a list before indexing with it. This key/value pair in the response doesn't seem to be used elsewhere, but I left it as a set for Chesterton's fence reasons.

Since this warning is surfaced with the first code snippet on the README, it's nice to avoid this warning

### CODE REVIEW

**Comment by talgalili** [comment]
Thanks! I'll take a look at it later today after the tests  finish running.

**Comment by ahakso** [comment]
Ah; so the attempt to assign the column with an attribute actually results in a no-op. When correcting the assignment, the target population gains a new column that is response variable, `happiness`. This breaks a test. 

Since we don't expect to have the response variable in the target population, my recommendation is just to remove the attempted assignment of the happiness column... Happy to do that if you like, or we can leave as is and update the test to expect the response variable in the target

**Comment by talgalili** [comment]
I'll take a look within an hour once I'm by a computer.
Thanks!

**Comment by talgalili** [comment]
Hey @ahakso 
I took a look, thanks for the PR!
Both changes seems good to me.
Before I import it, could you please just update the CHANGELOG file with your fixes? (you can add a "Bug Fixes" section to 0.9.0 release)

https://github.com/facebookresearch/balance/blob/main/CHANGELOG.md

**Comment by ahakso** [comment]
Great - yes, tests pass locally, but not in the workflow. I'll see if I can figure out why the random draws differ and update the changelog; thanks

**Comment by talgalili** [comment]
@ahakso thinking about it - I have a guess on why this would fail.
The random seed is set at the beginning, and every call to another function that creates random values will (conceptually) move the random seed for the next function. So when removing a line that creates random numbers, the following calls will produce different random numbers - which will lead the tests to fail.

I think the easiest solution would be to get the target_df.happiness back, and update the tests.

WDYT?

**Comment by ahakso** [comment]
Yep, had just come to come to the same realization myself... My local tests were passing because the imports in pytest are importing from the pip-installed balance 🤦 

That's a reasonable option, but I like that the target population df is currently missing the measured `happiness` value that the sample is trying to estimate for the population. And if we add happiness to it, we'll need to add the resulting hardcoded values to the test in any case. Any objection to me just changing the hardcoded expected test values downstream of the removed random number generation?

**Comment by talgalili** [comment]
The original point of having happiness in the target was to see what the
real population value is.
It's not a realistic case, of course, but it allows to discuss how close
the adjustment is getting us to the "real" value.

WDYT?

**Comment by ahakso** [comment]
That seems reasonable. I'll go ahead & do that.

**Comment by talgalili** [comment]
Thanks!
I'll run the tests and if they're green I'll get the PR merged during the day tomorrow (I'll need a aign off by another reviewer before it's merged. It should take less than a day)

**Comment by talgalili** [comment]
I fixed some linting warnings, and fixed the CHANGELOG a bit.
The PR should land within the next 30 minutes.

**Comment by talgalili** [comment]
PR merged, thanks for your contribution.

**Comment by talgalili** [comment]
BTW, a followup PR to this would be to update the tutorials a bit so happiness is defined as a target for the target population.

Just a thought.

**Comment by ahakso** [comment]
True, I'll do that if I get the chance. There are also a fairly significant number of additional deprecating operations here that would be nice (but less visible) to address. 

This was my first open source contribution, tiny as it was. Thanks for making it a perfectly pleasant experience!

**Comment by talgalili** [comment]
My pleasure!

I'd be happy to support whichever other contribution you'd be interested in
making.
The package still has many legacy issues to resolve which we have not yet
gotten to address, so any help would be appreciated.

(P.s.: I've added a "thank you" to you in the CHANGELOG)

**Pull request closed without merging**
